
export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';

export const FETCH_ARTICLE_HOME_PAGE = 'FETCH_ARTICLE_HOME_PAGE';
export const FETCHING_ARTICLE_HOME_PAGE = 'FETCHING_ARTICLE_HOME_PAGE';
export const FETCHED_ARTICLE_HOME_PAGE = 'FETCHED_ARTICLE_HOME_PAGE';

export const UPDATING_PAGINATION_ARTICLES_HOME_PAGE = 'UPDATING_PAGINATION_ARTICLES_HOME_PAGE';
export const UPDATED_PAGINATION_ARTICLES_HOME_PAGE = 'UPDATED_PAGINATION_ARTICLES_HOME_PAGE';

export const UPDATE_TAB_ARTICLES_HOME_PAGE = 'UPDATE_TAB_ARTICLES_HOME_PAGE';
export const UPDATING_TAB_ARTICLES_HOME_PAGES = 'UPDATING_TAB_ARTICLES_HOME_PAGES';
export const UPDATED_TAB_ARTICLES_HOME_PAGES = 'UPDATED_TAB_ARTICLES_HOME_PAGES';

export const FETCH_TAGS_HOME_PAGE = 'FETCH_TAGS_HOME_PAGE';
export const FETCHING_TAGS_LIST = 'FETCHING_TAGS_LIST';
export const FETCHED_TAGS_LIST = 'FETCHED_TAGS_LIST';